config/routes.rb
Rails.application.routes.draw do
  get 'home/index', to: 'home#index'
  get '/static_pages/contact', to: 'static_pages#contact'
  get 'static_pages/team', to: 'static_pages#team'
  get 'welcome/:user_entry', to: 'welcome#show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
    has_many :users
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :jointablegossiptags
  has_many :tags, through: :jointablegossiptags
end

app/models/join_table_gossip_tag.rb
class JoinTableGossipTag < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :jointablegossiptags
    has_many :gossips, through: :jointablegossiptags
end

app/models/user.rb
class User < ApplicationRecord
    belongs_to :city
    has_many :gossips
    has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
    has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController
    
    class GossipsController < ApplicationController
        def show
     
        end
      end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @gossips = Gossip.all
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def team
  end

  def contact
  end

  def welcome
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def show
    puts  params[:user_entry]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/home/index.html.erb
<div class="container">

<div class = "dive">

  <% @gossips.each do |gossip|%>

    <div class="card text-center">
      <div class="card-header">
        Youpi des potins
      </div>

      <div class="card-body">
        <h5 class="card-title"><%= gossip.title %></h5>
        <p class="card-text"><%= gossip.user.first_name %> <%= gossip.user.last_name %></p>
        <a href="<%=show_path(gossip.id)%>" class="btn btn-primary">Lire</a>
      </div>

      <div class="card-footer text-muted">
        <%=gossip.created_at%>
      </div>


    </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <title>GossipProjectV3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
     <header>
  <div class="bg-dark fixed-top">  
   <div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <h3 class="nav-item" ><a href="https://www.dailymotion.com/video/x821y1">Bienvenue chez la T.P Family </a></h3>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active"><a class="nav-link" href="#">Accueil<span class="sr-only"(current)></span> </a></li>
          <li><a class="nav-link" href="#">Les gossips</a></li>
         <%= link_to "Team", static_pages_team_path %>
         <%= link_to "Contact", static_pages_contact_path %>
        </ul>
      </div>
      </nav>
    </div>
  </div>
  </header>
  </body>
</html>

app/views/static_pages/contact.html.erb
<div class = "mt-5 mx-3">
    <h1>Coordonnées</h1>
    <p>Email: tpfamily@email.com</p>
    <p>Tel: + 555-4823</p>
</div>

app/views/static_pages/team.html.erb
<div class = "mt-5 mx-3">
    <h1>La T.P Family</h1>
    <ul>
        <li>Matthieu</li>
        <li>Mathieu</li>
        <li>Archie</li>
        <li>Gus</li>
    </ul>
</div>

app/views/welcome/show.html.erb
<div class = "mt-5 mx-3">
    <h1>Bienvenue <%=params[:user_entry]%></h1>
    <p>Youpi des potins</p>
</div>